version: '3.8'

services:
  wso2am:
    image: wso2/wso2am:latest  # Reemplaza con la versión que necesites
    container_name: wso2am
    privileged: true  # Solo para desarrollo
    ports:
      - "9443:9443"  # Consola de administración
      - "8243:8243"  # API Gateway SSL
      - "8280:8280"  # API Gateway
      - "8290:8290"
    volumes:
      - ./wso2am/repository/conf:/home/wso2carbon/wso2am-4.3.0/repository/conf
      # - ./wso2am/config:/home/wso2carbon/wso2am/repository/conf
    environment:
      - USER_MEM_ARGS=-Xms1024m -Xmx2048m -XX:+UseG1GC
      - JAVA_OPTS=-Dfile.encoding=UTF-8
    networks:
      - wso2-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0  # Utiliza una versión compatible de MongoDB
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - wso2-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3000"  # Puerto expuesto para el servicio de usuarios
    environment:
      - MONGO_URI=mongodb://mongodb:27017/userdb
      - PORT=3000
    networks:
      - wso2-network
    depends_on:
      - mongodb

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3002:3000"  # Puerto expuesto para el servicio de productos
    environment:
      - MONGO_URI=mongodb://mongodb:27017/productdb
      - PORT=3000
    networks:
      - wso2-network
    depends_on:
      - mongodb

  car-brands-service:
    build: ./car-brands-service
    container_name: car-brands-service
    ports:
      - "3003:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cardb
      - PORT=3000
    networks:
      - wso2-network
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"  # Puerto expuesto para el front-end
    networks:
      - wso2-network
    depends_on:
      - wso2am
  
  nginx:
    image: nginx
    ports:
      - "8080:80"  # Puerto del NGINX
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - wso2-network
    depends_on:
      - frontend

networks:
  wso2-network:
    driver: bridge

volumes:
  mongo_data:
