[server]
hostname = "67.205.143.93"
node_ip = "67.205.143.93"

[apim.gateway.environment]
http_endpoint = "http://67.205.143.93:8280"
https_endpoint = "https://67.205.143.93:8243"

[apim.devportal]
url = "https://67.205.143.93:9443/devportal"

[apim.publisher]
url = "https://67.205.143.93:9443/publisher"
